#!/bin/sh

VERSION=0.0.5
DEVICE_NAME=volant

volant_init()
{
  local container=$1
  local image=$2

  if [ "$image" = "" ]; then
    echo "The image is blank. Please set the image."
    exit 1
  fi

  lxc init $image $container

  if [ $? -ne 0 ]; then
    echo "Error creating this container."
    exit 1
  fi

  volant_commit $container
}

volant_delete()
{
  local container=$1

  lxc delete $container

  if [ $? -ne 0 ]; then
    echo "Error deleting this container."
    exit 1
  fi
}

volant_start()
{
  local container=$1
  local host_dir=$2
  local guest_dir=$3
  local revision=`lxc info $container | grep -E 'snap[0-9]+' | tail -n 1 | awk '{print $1}'`

  lxc restore $container $revision

  if [ $? -ne 0 ]; then
    echo "Error while restoring this container."
    exit 1
  fi

  volant_device_add $container $host_dir $guest_dir

  lxc start $container

  if [ $? -ne 0 ]; then
    echo "Error while starting this container."
    exit 1
  fi
}

volant_stop()
{
  local container=$1
  local host_dir=$2
  local guest_dir=$3

  lxc stop $container

  if [ $? -ne 0 ]; then
    echo "Error while stopping this container."
    exit 1
  fi

  volant_device_remove $container $host_dir $guest_dir
}

volant_run()
{
  local container=$1
  local host_dir=$2
  local guest_dir=$3
  local volantfile=$4

  lxc exec $container -- bash -c "cd $guest_dir; bash $volantfile"
}

volant_exec()
{
  local container=$1
  local host_dir=$2
  local guest_dir=$3
  local work_dir=$4
  shift 4

  lxc exec $container -- bash -c "cd $guest_dir; cd $work_dir; exec $*"
}

volant_commit()
{
  local container=$1

  lxc snapshot $container

  if [ $? -ne 0 ]; then
    echo "Error during snapshot of this container."
    exit 1
  fi
}

volant_rollback()
{
  local container=$1
  local count=`lxc info $container | grep -E 'snap[0-9]+' | awk '{print $1}' | wc -w`

  if [ $count -le 1 ]; then
    echo "This container can not be rolled back any more."
    exit 1
  fi

  local revision=`lxc info $container | grep -E 'snap[0-9]+' | tail -n 1 | awk '{print $1}'`
  lxc delete $container/$revision

  if [ $? -ne 0 ]; then
    echo "Error deleting this container."
    exit 1
  fi

  local revision=`lxc info $container | grep -E 'snap[0-9]+' | tail -n 1 | awk '{print $1}'`
  lxc restore $container $revision

  if [ $? -ne 0 ]; then
    echo "Error while restoring this container."
    exit 1
  fi
}

volant_device_add()
{
  local container=$1
  local host_dir=$2
  local guest_dir=$3

  lxc config device add $container $DEVICE_NAME disk source=$host_dir path=$guest_dir 1> /dev/null

  if [ $? -ne 0 ]; then
    echo "Error adding device to this container."
    exit 1
  fi
}

volant_device_remove()
{
  local container=$1
  local host_dir=$2
  local guest_dir=$3

  lxc config device remove $container $DEVICE_NAME 1> /dev/null

  if [ $? -ne 0 ]; then
    echo "Error deleting device from this container."
    exit 1
  fi
}

volant_exit_if_exists()
{
  local container=$1
  local name=$(lxc list $container --format csv -c n)

  if [ "$name" != "" ]; then
    echo "This container exists."
    exit 1
  fi
}

volant_exit_if_not_exists()
{
  local container=$1
  local name=$(lxc list $container --format csv -c n)

  if [ "$name" = "" ]; then
    echo "This container does not exist."
    exit 1
  fi
}

volant_exit_if_started()
{
  local container=$1
  local status=$(lxc list $container --format csv -c s)

  if [ "$status" = "RUNNING" ]; then
    echo "This container is running."
    exit 1
  fi
}

volant_exit_if_stopped()
{
  local container=$1
  local status=$(lxc list $container --format csv -c s)

  if [ "$status" = "STOPPED" ]; then
    echo "This container is stopped."
    exit 1
  fi
}

usage()
{
  cat <<EOF
Usage:

  volant <command> <arguments...> [options...]

Description:

  This 'volant' creates a container with immutable lxc. This container can be repeatedly tested.

Command:

  volant init <image>

  volant delete

  volant start

  volant stop

  volant status

  volant run

  volant exec [--work-dir path] -- <arguments...>

  volant commit

  volant rollback

  volant info

  volant list

Options:

  --version                 this version

  -h, --hellp               print this help text
EOF
}

version()
{
  echo "volant version $VERSION"
}

while true
do
  case "$1" in
    init|delete| \
    start|stop|status| \
    run|exec| \
    commit|rollback| \
    info|list)
                         COMMAND=$1; shift 1;;
    --work-dir)          work_dir=$2; shift $(( $# >= 2 ? 2 : 1 ));;
    --)                  shift 1; ARGV=$*;;
    -h|--help)           usage; exit 0;;
    --version)           version; exit 0;;
    *)                   break;;
  esac
done

if [ "$volantfile" = "" ]; then
  volantfile=Volantfile.sh
fi

if [ ! -e "$volantfile" ]; then
  echo "This '$volantfile' file does not exist."
  exit 1
fi

if [ ! -e .cache ]; then
  mkdir -p .cache
fi

if [ -e ".cache/name" ]; then
  container=`cat .cache/name`
else
  container=vm-`date | md5sum | awk '{print substr($1, 0, 9)}'`
  echo $container > .cache/name
fi

if [ "$host_dir" = "" ]; then
  host_dir=`pwd`
fi

if [ "$guest_dir" = "" ]; then
  guest_dir=/volant
fi

if [ "$work_dir" = "" ]; then
  work_dir=.
fi

if [ "$COMMAND" = "" ]; then
  usage && exit 1
fi

case "$COMMAND" in
  init)
    volant_exit_if_exists $container
    volant_init $container $*
    ;;
  delete)
    volant_exit_if_not_exists $container
    volant_exit_if_started $container
    volant_delete $container
    ;;
  start)
    volant_exit_if_not_exists $container
    volant_exit_if_started $container
    volant_start $container $host_dir $guest_dir
    ;;
  stop)
    volant_exit_if_not_exists $container
    volant_exit_if_stopped $container
    volant_stop $container $host_dir $guest_dir
    ;;
  status)
    volant_exit_if_not_exists $container
    lxc list $container --format csv -c s
    ;;
  run)
    volant_exit_if_not_exists $container
    volant_exit_if_stopped $container
    volant_run $container $host_dir $guest_dir $volantfile
    ;;
  exec)
    volant_exit_if_not_exists $container
    volant_exit_if_stopped $container
    volant_exec $container $host_dir $guest_dir $work_dir $ARGV
    ;;
  commit)
    volant_exit_if_not_exists $container
    volant_exit_if_started $container
    volant_commit $container
    ;;
  rollback)
    volant_exit_if_not_exists $container
    volant_exit_if_started $container
    volant_rollback $container
    ;;
  info)
    volant_exit_if_not_exists $container
    lxc info $container
    ;;
  list)
    lxc list
    ;;
  *)
    usage && exit 1
    ;;
esac

